services:
  - type: web
    name: product-importer-api
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: |
      sh -c "
      celery -A app.celery_app.celery_app worker --loglevel=info --pool=solo &
      uvicorn app.main:app --host 0.0.0.0 --port 10000
      "
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: product-importer-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: product-importer-redis
          property: connectionString

  - type: redis
    name: product-importer-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow internal services

databases:
  - name: product-importer-db
    plan: free
